# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: Théories
    submenu:
        - name: La relativité
          link: /theories/relativite
        - name: La dilatation temporelle
          link: /theories/dilatation-temporelle
  - name: Technologies presentes
    submenu: 
        - name: Les satéllites
          link: /technologies-presentes/satellites
        - name: La station spatiale internationale
          link: /technologies-presentes/station-spatiale
  - name: Technologies futures
    submenu: 
        - name: Les voyages intersidéraux
          link: /technologies-futures/voyages-intersideraux
        - name: Les voyages temporels
          link: /technologies-futures/voyages-temporels