# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: Théories
    submenu:
        - name: La relativité
          link: /theories/relativite
        - name: La dilatation temporelle
          link: /theories/Dilatation temporelle
  - name: Technologies présentes
    submenu: 
        - name: Les avions supersoniques
          link: /technologies presentes/Avion supersonique
        - name: Les satellites
          link: /technologies presentes/Satellites
  - name: Technologies futures
    submenu: 
        - name: Les voyages intersidéraux
          link: /technologies futures/voyage intersideral
        - name: Les voyages temporels
          link: /technologies futures/voyage temporel
  - name: conclusion
    link: /conclusion
  - name: Sources
    link: /sources