# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: Théories
    submenu:
        - name: La relativité
          link: théories/relativité
        - name: La dilatation temporelle
          link: théories/dilatation-temporelle
  - name: Technologies présentes
    submenu: 
        - name: Les satéllites
          link: technologies-présentes/satéllites
        - name: La station spatiale internationale
          link: technologies-présentes/station-spatiale
  - name: Technologies futures
    submenu: 
        - name: Les voyages intersidéraux
          link: technologies-futures/voyages-intersidéraux
        - name: Les voyages temporels
          link: technologies-futures/voyages-temporels